### ISSUE TITLE
[Question] OAuth2Client getMetadata return Object

### ISSUE THREAD

**Issue by stefanorg** [ory/hydra-client-java#1]
Hi,
from version 1.3.x client.getMetadata() return Object.

Why this isn't anymore a Map<String, Object> ?

Thanks

**Comment by aeneasr** [comment]
We autogenerate the code using openapi-generator so I don't really have an answer for you.

**Comment by stefanorg** [comment]
ok, hi think the openapi-generator 4.2.3 changed the return type.
Anyway is it's runtime type is a `LinkedTreeMap` so i can cast it to `Map<String, Object>`

thank you

**Comment by stefanorg** [comment]
i think this can be closed.
