### ISSUE TITLE
Support for hydra v1.10.7

### ISSUE THREAD

**Issue by PhilippauxAdrien** [ory/hydra-client-java#11]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-java/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-java/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We upgraded to hydra version 1.10.7 but we are facing an issue with ConsentRequest model as a new field has been added in this version ;

Unrecognized field \"amr\" (class ConsentRequest)

Could you provide support for this version

### Describe your ideal solution

Add a new field "amr" in ConsentRequest class

### Workarounds or alternatives

Rewrite our own ConsentRequest class and overwrite the existing one.

### Version

1.9.0

**Comment by aeneasr** [comment]
If you use Ory Hydra 1.9 you need to use an SDK in the same version :) Or did I misunderstand the problem?
