### ISSUE TITLE
document (and generate) the "scope" parameter in token endpoint

### ISSUE THREAD

**Issue by stefanorg** [ory/hydra-client-java#2]
Hi @aeneasr,
in the token endpoint documentation (https://www.ory.sh/hydra/docs/reference/api#the-oauth-20-token-endpoint) the optional `scope` parameter is missing and therefore when generating the client with the operapi generator, there is no way to pass a scope in a client_credentials grant flow.

Clearly this is supported by hydra

```
curl -u "username:secret" -d "grant_type=client_credentials&scope=system" http://localhost:4444/oauth2/token
{"access_token":"idCzU_6Y8rYVpnjggAn900ut_VhjV4diPUHCFs3-z2w.YZUsVSMwPD11WVnOOXHRnk-IPw65HP-doa4Bs3UzPdE","expires_in":3599,"scope":"system","token_type":"bearer"}
```

Maybe it is usefull to add that parameter and let the generator generate the missing scope field.

Thank you

**Comment by aeneasr** [comment]
Thank you! If you want, you can add the scope parameter here: https://github.com/ory/hydra/blob/master/oauth2/doc.go#L163

This will then end up in the SDK
