### ISSUE TITLE
Is version "v1.10.3" released?

### ISSUE THREAD

**Issue by UkonnRa** [ory/hydra-client-java#6]
* Is the version "v1.10.3" released? I cannot find it on https://search.maven.org/artifact/sh.ory.hydra/hydra-client.
* Why there is a prefix "v" in this release?

**Comment by aeneasr** [comment]
Sometimes the release pipeline fails but 1.10.2 is equivalent to .3

Because that’s how we version things, following semver standard an format

**Comment by UkonnRa** [comment]
But I still cannot find 1.10.x on maven central?

![Screenshot_2021-05-27-19-16-51-188_com.android.chrome.jpg](https://user-images.githubusercontent.com/16066720/119817162-415d7780-beb3-11eb-95aa-e1b583537cd8.jpg)

**Comment by aeneasr** [comment]
Right, we had some issues with the SDK release pipeline. The next release should show up on maven again. Unfortunately, the maven release process is f'ing terrible 😞
