### ISSUE TITLE
Potential release date for version 1.10.5

### ISSUE THREAD

**Issue by characode** [ory/hydra-client-java#8]
Potential release date for version 1.10.5 in maven, I see there was a previous issue with 1.10.3 and wanted to determine if there was a potential date for 1.10.5?

**Comment by aeneasr** [comment]
We are having some issues with the SDK pipeline and maven, I will look into it in the coming days!

**Comment by characode** [comment]
@aeneasr  Thank you for taking a look. I had failures trying to build this locally however it works if I add back in this [dependency](https://github.com/ory/sdk/commit/042c25cad8e098352b14dfddcff718c29aa70a3c#diff-8aa0cd037b4a40d2c17766678ce671e0db0fed5c5e2874d1e27e4066e5e2dd85L316)

**Comment by aeneasr** [comment]
This works now :)

**Comment by jiayx** [comment]
> This works now :)

The v1.10.6 can't find on https://search.maven.org/artifact/sh.ory.hydra/hydra-client. Are there other problems
